#!/bin/bash

# export __NV_PRIME_RENDER_OFFLOAD=1
# export __VK_LAYER_NV_optimus=NVIDIA_only
# export __GLX_VENDOR_LIBRARY_NAME=nvidia
# export __GL_YIELD=USLEEP
# export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json

# exec "$@"

__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
