#!/bin/bash


# Kitty Terminal
dnf install kitty


# Ghostty Terminal
dnf copr enable pgdev/ghostty

dnf install ghostty


# Hyprland
dnf copr enable solopasha/hyprland

dnf install hyprland hyprland-devel hypridle hyprlock hyprpaper hyprnome hyprpolkitagent xdg-desktop-portal-hyprland rofi waybar wlogout


# Browser
dnf install qutebrowser


# Utils
dnf install network-manager-applet blueman



# dnf remove kitty

# dnf remove ghostty

# dnf remove hyprland hyprland-devel hypridle hyprlock hyprpaper hyprnome hyprpolkitagent xdg-desktop-portal-hyprland rofi waybar wlogout

# dnf remove qutebrowser

# dnf remove network-manager-applet blueman
